# Generated by Django 6.0.4 on 2026-05-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesssetting',
            old_name='privacy_policy',
            new_name='legal_privacy_policy',
        ),
        migrations.RenameField(
            model_name='businesssetting',
            old_name='terms_of_service',
            new_name='legal_terms_of_use_policy',
        ),
    ]
