# Generated by Django 6.0.4 on 2026-05-13 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportreply_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportquery',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='supportquery',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='supportreply',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
