# Generated by Django 6.0.4 on 2026-05-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_supportquery_is_answered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supportreply',
            options={'ordering': ['created_at']},
        ),
    ]
