# Generated by Django 6.0.4 on 2026-05-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocument',
            options={'ordering': ['-submitted_at']},
        ),
    ]
