# Generated by Django 6.0.4 on 2026-07-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('others', 'Others'), ('industry_updates', 'Industry Updates'), ('resources', 'Resources')], default='others', max_length=50),
        ),
    ]
