# Generated by Django 6.0.4 on 2026-04-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('is_eb_5_enabled', models.BooleanField(default=False)),
                ('total_project_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('roi', models.CharField(max_length=16)),
                ('job_impact', models.CharField(max_length=16)),
                ('business_plan', models.FileField(upload_to='projects/business_plans/')),
                ('financial_report', models.FileField(upload_to='projects/financial_reports/')),
                ('legal_document', models.FileField(upload_to='projects/legal_documents/')),
                ('agreement', models.FileField(upload_to='projects/agreements/')),
                ('banner', models.ImageField(upload_to='projects/banners/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
