# Generated by Django 6.0.4 on 2026-06-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='projects/agreements/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='projects/banners/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to='projects/business_plans/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='financial_report',
            field=models.FileField(blank=True, null=True, upload_to='projects/financial_reports/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='legal_document',
            field=models.FileField(blank=True, null=True, upload_to='projects/legal_documents/'),
        ),
    ]
