# Generated by Django 6.0.4 on 2026-04-28 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('current_country_of_residence', models.CharField(max_length=50)),
                ('source_of_funds', models.CharField(max_length=255)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_strategy', models.CharField(choices=[('immigration', 'Immigration'), ('profit', 'Profit'), ('both', 'Both')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('passport_copy', models.FileField(upload_to='investments/passport_copies/')),
                ('proof_of_address', models.FileField(upload_to='investments/proof_of_address/')),
                ('proof_of_funds', models.FileField(upload_to='investments/proof_of_funds/')),
                ('bank_statements', models.FileField(upload_to='investments/bank_statements/')),
                ('upload_agreement', models.FileField(upload_to='investments/agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
