# Generated by Django 6.0.4 on 2026-06-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='bank_statements',
            field=models.FileField(blank=True, null=True, upload_to='investments/bank_statements/'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='investments/passport_copies/'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='investments/proof_of_address/'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='proof_of_funds',
            field=models.FileField(blank=True, null=True, upload_to='investments/proof_of_funds/'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='upload_agreement',
            field=models.FileField(blank=True, null=True, upload_to='investments/agreements/'),
        ),
    ]
